### ISSUE TITLE
*.sch-bak files looks like distraction

### ISSUE THREAD

**Issue by rusefillc** [DanielMartensson/STM32-PLC#3]
Looks like without a .gitignore some less useful files have made into this repo like *.sch-bak

Is there any interest for me to PR removal and some .gitignore?

**Comment by DanielMartensson** [comment]
Excuse me, can you explain?

**Comment by rusefillc** [comment]
![image](https://github.com/DanielMartensson/STM32-PLC/assets/48498823/2352d865-c0dc-43c7-9ff7-f18a5bf76aee)

GIT is version control system right? When we use version control we address the need for backup files (sch-bak) with GIT approach not file based approach?

**Comment by DanielMartensson** [comment]
This file is a backup file from KiCad.

**Comment by rusefillc** [comment]
Yes, that's a backup file from KiCad. That's exactly why it should not be published in any git repository.

**Comment by DanielMartensson** [comment]
Does it matter? I mean, it's just a simple backup file.
