### ISSUE TITLE
official gerbers?

### ISSUE THREAD

**Issue by rusefillc** [DanielMartensson/STM32-PLC#4]
Are gerber files not universal enough for this repo to have official artifacts?

Also there is that one single amazingly cheap fabrication shop with PCB assembly files, an official BOM + placement file would allow for simpler fabrication.

**Comment by DanielMartensson** [comment]
I don't know what you mean. I have been using gerber files for JLCPCB.

**Comment by rusefillc** [comment]
DanielMartensson says 'download kicad, click "export", make sure not to mess up, export gerbers, make sure not to forget to export drill file separately"

https://github.com/rusefi/hw_microRusEfi/tree/master/gerbers/R0.6.0 is an example of an alternative approach which would be "oh you want to just USE our hardware? here are gerbers no need to leard kicad"

I suggest a usability improvement for people who just want hardware as is

**Comment by DanielMartensson** [comment]
Well, to build this project, you need to know what you are doing. This is not a beginner example.

**Comment by rusefillc** [comment]
@DanielMartensson only people capable of kicad are capable to solder? What about Altium professionals, would they all NOT be able to solder?

Actually here is another idea: humans should not be soldering this project. Humans should have a choice of using JLCPCB assembly services and let machines solder components on PCBs.

**Comment by DanielMartensson** [comment]
I don't know what I will answer to that.
