### ISSUE TITLE
official binaries?

### ISSUE THREAD

**Issue by rusefillc** [DanielMartensson/STM32-PLC#5]
why torture users with a UI IDE? since this is DONE maybe help potential users with official binaries?

in six years from now it would be much easier to have binaries instead of trying to find a matching version of the IDE

**Comment by DanielMartensson** [comment]
What's wrong with STM32CubeIDE?

**Comment by rusefillc** [comment]
Nothing is wrong with STM32CubeIDE today.

I am speaking about 
* usability for end users
* long term risk

in 6 years from today there is a good chance that newer STM32CubeIDE would not open current project. in 6 years there is a good chance that older version would be either hard to get or would refuse to install along side current version. C'mon, compiler warning/error behavior for corner cases changes every couple of years, Windows vs Linux versions of same compiler are themselves compiled with different flags! In my opinion a better way to open source is a combination of source code AND official binaries.

**Comment by DanielMartensson** [comment]
ST will always provide support to migrate old projects to new projects.

But I'm posting the source code?

**Comment by rusefillc** [comment]
@DanielMartensson you are placing too much faith in ST. They are humans, they have defects and sometimes they do not fix those defect for years.

**Comment by DanielMartensson** [comment]
@rusefillc  Yes I know. But at least they trying to build tools that are very easy to use. Also ST mcu are very cheap.
